---
title: "Kazutan.R"
output:
  html_document:
    toc: false
---

このサイトは、私がこれまで書いてきたR関連の資料をまとめています。随時更新していく予定です。  
目的やSessionInfoについてはメニューバーの**about**を参照してください。

<div class="panel panel-info">
  <div class="panel-heading">2017/7/30のハンズオン資料について</div>
  <div class="panel-body">
私が担当するハンズオンの資料を、以下のリンク先に設置しています:

https://kazutan.github.io/kazutanR/hands_on_170730/index.html

現在は列選択と行選択のみですが、開催時刻には公開します。
  </div>
</div>


# {.row}

## Contents {.col-md-8}

### データ操作

- [データセットの操作](data_handling.html)(dplyr, tidyr)
    - dplyr, tidyrを利用したデータセットの操作
- [文字列の操作](stringr-intro.html)(stringr)
    - stringrを利用した文字列データの操作
- [factor型データの操作](forcats_test.html)(forcats)
    - forcatsを利用したfactor型データの操作

### 可視化

- [ggplot2によるPlot](ggplot2_links.html)
    - ggplot2を利用したデータの可視化に関する資料リンク
- [DTによる表作成](DT_demo.html)
    - DTを利用したインタラクティブな表の作成
- [leafletによる地図作成](leaflet_d.html)
    - leafletを利用した地図およびデータプロットの作成

### R Markdown

- [R Markdown入門](Rmd_intro.html)
    - R Markdownによるドキュメント生成とスライド生成の基礎的な内容
- [R Markdownでダッシュボード作成](fdb_intro.html)
    - flexdashboardを利用してダッシュボードを作成

### その他

- [webshotによるWebページキャプチャ](webshot_demo.html)
    - webshotを利用したWebページのキャプチャと応用
- [corrrによる相関行列の操作・可視化](corrr_test.html)
    - corrrパッケージを利用して，いい感じで相関行列を処理

### 小ネタ集

- ggplot2で中央から左右に開いた棒グラフ(2017/3/7)
    - いわゆる人口ピラミッドみたいな図をggplot2で
- 状態遷移図の可視化(2017/03/06)
    - {DiagrammeR}と{networkD3}でちょっとやってみた

## News {.col-md-4 .news}
- 2017/3/7
    - R Markdownに「R Markdownでダッシュボード作成」を追加
    - トップページのリンクを調整
    - R Markdown入門の見出しレベル調整
    - 小ネタ集に「ggplot2で中央から左右に開いた棒グラフ」を追加
- 2017/3/6
    - 小ネタ集設置
    - 小ネタ集に状態遷移図の可視化を追加
- 2017/3/4
    - R MarkdownにR Markdown入門を追加
- 2017/3/1
    - その他にcorrrを追加
    - Homeの内容変更とNavBar修正
    - aboutを追加
    - dplyr&tidyr, forcatsのsessioninfoを削除
- 2017/2/28
    - その他にwebshotを追加
    - 可視化のggplot2内でうまく表示できていなかったものを修正
    - デザイン微修正
- 2017/2/22
    - 可視化にggplot2を追加
- 2017/2/21
    - 可視化にDT, leafletを追加
    - データ操作にdplyr&tidyr，stringr, forcatsを追加
